url: "https://jaclynpasquale.github.io"
baseurl: ""

# Site settings
title: Jaclyn Pasquale
email: jaclynpasquale@gmail.com
description: "The personal portfolio site of Jaclyn Pasquale, Web Developer and Designer. Graduate of Cohort 7 of Nashville Software School"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: CAC640
  secondary: 195a4e
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Jaclyn Pasquale
  pic: Jaclyn_square_color
  position: Web Developer & Designer
  social:

    - title: github
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: github
    url: http://github.com/JaclynPasquale
  - title: linkedin
    url: http://www.linkedin.com/in/jaclynpasquale

# # Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
